pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'sudo apt-get update'
                sh 'sudo apt-get install -y python3 python3-pip'
                sh 'pip3 install -r requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh 'python3 -m pytest tests/'  // cSpell:ignore pytest
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'echo "Deploying application on Ubuntu..."'
                sh 'python3 src/app.py &'
            }
        }
    }
}