pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'sudo apt-get update'
                sh 'sudo apt-get install -y python3 python3-pip python3-venv'
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh './venv/bin/python -m pytest tests/'  // cSpell:ignore pytest
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'echo "Deploying application on Ubuntu..."'
                sh './venv/bin/python src/app.py &'
            }
        }
    }
}