pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh 'python -m pytest tests/'  // cSpell:ignore pytest
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'echo "Deploying application..."'
            }
        }
    }
}