---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Deploy application
  copy:
    src: "{{ app_source }}"
    dest: /opt/app/
  notify: restart app