---
- name: Install Python
  package:
    name: python3
    state: present

- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Deploy application
  copy:
    src: "{{ app_source }}"
    dest: /opt/app/
  notify: restart app